import os
import requests
import smtplib
from dotenv import load_dotenv
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

load_dotenv()

NEWS_API_KEY = os.getenv("NEWS_API_KEY")

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")


def fetch_top_headlines():
    url = "https://newsapi.org/v2/top-headlines"

    params = {
        "country": "us",
        "category": "technology",
        "pageSize": 5,
        "apiKey": NEWS_API_KEY
    }

    response = requests.get(url, params=params)
    data = response.json()

    if data.get("status") != "ok":
        print("❌ Error fetching news:", data)
        return []

    return data.get("articles", [])


def format_news_email(articles):
    body = "🔥 Today's Top Tech Headlines 🔥\n\n"

    for i, article in enumerate(articles, start=1):
        title = article.get("title", "No Title")
        source = article.get("source", {}).get("name", "Unknown Source")
        url = article.get("url", "")

        body += f"{i}. {title}\n"
        body += f"   Source: {source}\n"
        body += f"   Link: {url}\n\n"

    body += "\n---\nGenerated by AWS SES Newsletter Project 🚀"
    return body


def send_newsletter_email(subject, body):
    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
        server.starttls()
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        server.quit()

        print("✅ Newsletter Email Sent Successfully!")

    except Exception as e:
        print("❌ Error sending email:", e)


if __name__ == "__main__":
    articles = fetch_top_headlines()

    if articles:
        email_body = format_news_email(articles)
        send_newsletter_email("🔥 Daily Tech Newsletter", email_body)
    else:
        print("❌ No news found, email not sent.")